### ISSUE TITLE
Server misbehaving

### ISSUE THREAD

**Issue by mzihin91** [inlets/inlets#218] opened 2021-03-22 10:21 UTC
Unable to connect to the exit server if inlets client is behind proxy and is running using daemontools.  

## Expected Behaviour

If I run the client normally in the command line, everything works, but if I run the script using daemontools, it fails to connect to the exit server. If I run the script using the daemontools but in a different network (no proxy) is also working fine.

## Current Behaviour

This is the error output: 
Starting client - version 3.0.1
2021/03/22 14:57:46 Upstream: myurl.com => http://localhost:3000
time="2021/03/22 14:57:46" level=info msg="Connecting to proxy" url="wss://myurl.com/tunnel"
time="2021/03/22 14:57:55" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp: lookup myurl.com on 128.100.1.1:53: server misbehaving"
time="2021/03/22 14:57:55" level=error msg="Remotedialer proxy error" error="dial tcp: lookup myurl.com on 128.100.1.1:53: server misbehaving"

## Steps to Reproduce (for bugs)

1. Use a DigitalOcean droplet as the exit server
2. Use a Raspberry Pi 4 Model B as the inlets client
3. The Raspberry Pi's network must be behind proxy
4. Run the inlets client using daemontools

## Context

I am using daemonttools to ensure that the tunnel connection can be re-established automatically.

## Your Environment

* inlets version `inlets --version` 
* 3.0.1

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):
* Raspbian Buster

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment] 2021-03-22 13:45
I'm sorry you're having difficulties. I have no idea what daemontools is, but it sounds like the root cause of your issues. I would suggest you use systemd or a docker container instead.

You may want to look at getting inlets PRO for personal use which has a generation command for the client and server along with built in TLS negating the need for your reverse proxy. 

I'm going to close the issue, but have given you direction as to what to do next. 

Alex

**Closed by alexellis** 2021-03-22 13:45 UTC

**Comment by mzihin91** [comment] 2021-03-23 01:28
Thank you for the help. I have tested using systemd and it gives the same error. Also, I am using Caddy as the reverse proxy in the exit server (cloud vm) which provides TLS and handles the subdomains. On the other side, the inlets client is behind the company's proxy.

**Comment by mzihin91** [comment] 2021-03-23 07:53
I got it to work by setting the environment variable: http_proxy and https_proxy using the envdir command if using daemontools

**Comment by alexellis** [comment] 2021-03-24 09:10
If you're using inlets for commercial purposes you may want to look at [inlets PRO](https://inlets.dev) which has built-in Let's Encrypt support and load-balancing of clients, and no need for reverse proxies or [becoming a sponsor for inlets on GitHub](https://github.com/sponsors/inlets) to help us maintain the project and give support to users like this.
